daemonset:
  # Include the daemonset
  enabled: true
  extraEnvs:
    - name: "ELASTICSEARCH_HOSTS"
      valueFrom:
        secretKeyRef:
          name: es-credentials
          key: hosts
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: es-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: es-credentials
          key: password
  secretMounts: NULL
deployments:
  secretMounts: NULL
