apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitoring-sentinel-${namespace}
  namespace: prometheus
  labels:
    release: prometheus
    redis-operator: "true"
spec:
  selector:
    matchLabels:
      redis_setup_type: sentinel
  endpoints:
    - port: redis-exporter
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - ${namespace}
